addSbtPlugin("com.github.philcali" % "sbt-lwjgl-plugin" % "3.1.5")
addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "0.8.0")
addSbtPlugin("de.johoop" % "findbugs4sbt" % "1.3.0")
addSbtPlugin("de.johoop" % "cpd4sbt" % "1.1.5")
addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.3.0")
